<?php
/* @var $proServices
 * @var $realtor
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include __DIR__ . '/../layout/realtor/header.phtml';?>
    <title>My Pro Services</title>
</head>
<body class="nav-fixed">
<?php include __DIR__ . '/../layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include __DIR__ . '/../layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="list"></i></div>
                                    Pro Services List
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <div id="formContainer" style="display: none">
                                    <form action="/pro-services/import" method="post" enctype="multipart/form-data">
                                        <input id="excelHomeProsfile" type="file" name="excelHomeProsfile" class="form-control-sm" style="width: 210px" accept=".csv,.ods, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" required>
                                        <input class="btn btn-sm btn-success" type="submit" name="submit" value="Confirm">
                                        <a id="backButton" class="btn btn-sm btn-secondary">Back</a>
                                    </form>
                                </div>
                                <div id="buttonsContainer">
                                    <a class="btn btn-sm btn-light text-primary" href="/pro-services/template-download">
                                        <i class="me-1" data-feather="download"></i>
                                        Download Pro Services Template
                                    </a>
                                    <a class="btn btn-sm btn-light text-primary" href="/pro-services/new">
                                        <i class="me-1" data-feather="plus"></i>
                                        Create New Pro Service
                                    </a>
                                    <a id="importProServicesButton" class="btn btn-sm btn-light text-primary">
                                        <i class="me-1" data-feather="plus"></i>
                                        Import Pro Services
                                    </a>
                                    <!--<a data-bs-toggle=tooltip data-bs-placement=bottom title='Download Template' href="<?/*='../Controller/template_download.php?template=pro_services'*/?>"><i class="fa-solid fa-download"></i></a>-->
                                </div>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="card">
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th>Company Name</th>
                                <th>Date Created</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Company Name</th>
                                <th>Date Created</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            foreach ($proServices as $proService)
                            {
                                $id = $proService->doc_id;
                                $companyName = $proService->company_name;
                                $createdAt = $proService->date;
                                $createdAtFormatted = $createdAt->get()->format("m-d-Y");
                                $showProServiceLink = "show?id=$id";
                                $editProServiceLink = "edit?id=$id";
                                $deleteProServiceLink = "delete?id=$id";
                                echo "
                                <tr>
                                    <td>$companyName</td>
                                    <td>$createdAtFormatted</td>
                                    <td class='text-center'>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$showProServiceLink><i data-feather='zoom-in'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$editProServiceLink><i data-feather='edit'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark' data-bs-toggle='modal' data-bs-target='#approveUserModal$id'><i data-feather='trash-2'></i></a>                                                                                                                              
                                    </td>                                                                                          
                                </tr>
                                
                                <div class='modal fade' id='approveUserModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalCenterTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-centered' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-header d-block'>
                                                <button class='btn-close float-end' type='button' data-bs-dismiss='modal' aria-label='Close'></button>
                                                <h5 class='modal-title text-center' id='exampleModalCenterTitle'>Removal Confirmation</h5>
                                            </div>
                                            <div class='modal-body text-center'>
                                                Do you really want to delete this pro service ?
                                            </div>
                                            <div class='modal-footer justify-content-center'>
                                                <a class='btn btn-secondary' type='button' data-bs-dismiss='modal'>No</a>
                                                <a class='btn btn-success' type='button' href='$deleteProServiceLink'>Yes</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                ";
                            };
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <?php include __DIR__ . '/../layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include __DIR__ . '/../layout/realtor/scripts.phtml';?>
<script>
    $( document ).ready(function() {
        $("#importProServicesButton").click(function () {
            $("#buttonsContainer").hide()
            $("#formContainer").show()
        })
        $("#backButton").click(function () {
            $("#formContainer").hide()
            $("#buttonsContainer").show()
        })
    });
</script>
</body>
</html>
