<?php
/* @var $errorMessage */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Change Master Password</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="lock"></i></div>
                                    Change Master Password
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-4">
                <div class="row">
                    <div class="col-xl-4">
                    </div>
                    <div class="col-xl-4">
                        <div class="card mb-4">
                            <div class="card-header text-center">New Master Password</div>
                            <div class="card-body">
                                <form action="/dashboard/change-master-password" method="post">
                                    <?php
                                    if(isset($errorMessage))
                                    {
                                        echo "<div class='alert alert-danger'>$errorMessage</div>";
                                    }
                                    ?>
                                    <div class="row gx-3 mb-1">
                                        <div class="mb-2">
                                            <label class="small mb-1" for="password">New Master Password</label>
                                            <input class="form-control" type="password" name="newMasterPassword" placeholder="Enter your new master password..." required/>
                                        </div>
                                    </div>
                                    <div class="row gx-3 mb-1">
                                        <div class="mb-2">
                                            <label class="small mb-1" for="password">Confirm Master Password</label>
                                            <input class="form-control" type="password" name="confirmMasterPassword" placeholder="Confirm your new master password..." required/>
                                        </div>
                                    </div>
                                    <div class="align-items-center justify-content-between mt-1 text-center">
                                        <input class="btn btn-success" type="submit" value="Save Changes">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4">
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
</body>
</html>
