<?php
/* @var $clients
 * @var $realtor
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>My Clients</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="list"></i></div>
                                    My Clients
                                </h1>
                            </div>
                            <div class="col mb-3">
                                <form id="selectedClientsForm" action="" method="post">
                                    <input type="hidden" class="selected_clients" name="selectedClients">
                                    <button type="submit" id="sendInviteButton" class="btn btn-sm btn-light text-primary" href="#" disabled>
                                        <i class="me-1" data-feather="send"></i>
                                        Send invitation to download App
                                    </button>
                                    <button data-bs-toggle=tooltip data-bs-placement=right title='Delete Selected Clients' type="submit" id="trashButton" class="btn btn-sm btn-light text-primary" href="#" disabled>
                                        <i class="me-1" data-feather="trash-2"></i>
                                    </button>
                                </form>
                                <!--<form id="customDeleteForm" action="/clients/custom-delete" method="post">
                                    <input type="hidden" class="selected_clients" name="selectedClientsCustomDelete">
                                    <button type="submit" id="trashButton" class="btn btn-sm btn-light text-primary" href="#" disabled>
                                        <i class="me-1" data-feather="trash-2"></i>
                                    </button>
                                </form>-->
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <div id="formContainer" style="display: none">
                                    <form action="/clients/import-from-file" method="post" enctype="multipart/form-data">
                                        <input id="excelcontactsfile" type="file" name="excelclientsfile" class="form-control-sm" style="width: 210px" accept=".csv,.ods, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" required>
                                        <input class="btn btn-sm btn-success" type="submit" name="submit" value="Confirm">
                                        <a id="backButton" class="btn btn-sm btn-secondary">Back</a>
                                    </form>
                                </div>
                                <div id="buttonsContainer">
                                    <a class="btn btn-sm btn-light text-primary" href="/clients/export-to-csv">
                                        <i class="me-1 fa-solid fa-file-export"></i>
                                        Export client list to .csv
                                    </a>
                                    <a class="btn btn-sm btn-light text-primary" href="/clients/template-download">
                                        <i class="me-1" data-feather="download"></i>
                                        Download Client Template
                                    </a>
                                    <a class="btn btn-sm btn-light text-primary" href="/clients/new">
                                        <i class="me-1" data-feather="plus"></i>
                                        Create New Client
                                    </a>
                                    <a id="importClientButton" class="btn btn-sm btn-light text-primary">
                                        <i class="me-1" data-feather="plus"></i>
                                        Import Clients
                                    </a>
                                </div>
                                <div>
                                </div>
                            </div>
                        </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <?php
                if(isset($successFlashMessage))
                {
                    echo "<div class='alert alert-success' role='alert'>$successFlashMessage</div>";
                }
                ?>
                <div class="card">
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th class='text-center' style='vertical-align: middle'><input type='checkbox' class="checkAll"></th>
                                <th class='text-center' style='vertical-align: middle'>Client name<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='vertical-align: middle'>Address</th>
                                <th class='text-center' style='vertical-align: middle'>City</th>
                                <th class='text-center' style='vertical-align: middle'>State</th>
                                <th class='text-center' style='vertical-align: middle'>Created At</th>
                                <th class='text-center' style='max-width: 70px; vertical-align: middle'>Email Invite Sent At<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='max-width: 70px; vertical-align: middle'>Client Signed-up At<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class="text-center" style='vertical-align: middle'>Actions</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th><input type='checkbox' class="checkAll"></th>
                                <th>Client name<i class="fas fa-sort float-end mt-1"></i></th>
                                <th>Address</th>
                                <th>City</th>
                                <th>State</th>
                                <th>Date Created</th>
                                <th>Date Email Invite Sent</th>
                                <th>Date Client Signed-up</th>
                                <th>Actions</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            foreach ($clients as $client)
                            {
                                $docId = $client->doc_id;
                                $clientName = $client->first_name_1 . " " . $client->last_name_1;
                                $address = $client->address_1;
                                $city = $client->city;
                                $state = $client->state;
                                if(isset($client->created_at)) {
                                    $createdAt = $client->created_at->get()->format("m-d-Y");
                                } else {
                                    $createdAt = "";
                                }
                                if(isset($client->email_invite_sent_at)) {
                                    $emailInviteSentDate = $client->email_invite_sent_at->get()->format("m-d-Y");
                                } else {
                                    $emailInviteSentDate = "";
                                }

                                if(isset($client->mobile_app_signed_up_at) && trim($client->mobile_app_signed_up_at) !== "") {
                                    $mobileAppSignedUpDate = $client->mobile_app_signed_up_at->get()->format("m-d-Y");
                                } else {
                                    $mobileAppSignedUpDate = "";
                                }
                                $id = $client->doc_id;
                                $showClientLink = "show?id=$id";
                                $editClientLink = "edit?id=$id";
                                $deleteClientLink = "delete?id=$id";
                                echo "
                                <tr>
                                    <td class='text-center' style='vertical-align: middle'><input type='checkbox' value=$docId></td>
                                    <td class='text-center' style='min-width: 140px; vertical-align: middle'>$clientName</td>
                                    <td class='text-center' style='max-width: 250px; vertical-align: middle'>$address</td>
                                    <td class='text-center' style='vertical-align: middle'>$city</td>
                                    <td class='text-center' style='vertical-align: middle'>$state</td>
                                    <td class='text-center' style='min-width: 70px; vertical-align: middle'>$createdAt</td>
                                    <td class='text-center' style='vertical-align: middle'>$emailInviteSentDate</td>
                                    <td class='text-center' style='vertical-align: middle'>$mobileAppSignedUpDate</td>
                                                        
                                    <td class='text-center'>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$showClientLink><i data-feather='zoom-in'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$editClientLink><i data-feather='edit'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark' data-bs-toggle='modal' data-bs-target='#approveUserModal$id'><i data-feather='trash-2'></i></a>                                                                                                                              
                                    </td>
                                </tr>
                                
                                <div class='modal fade' id='approveUserModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalCenterTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-centered' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-header d-block'>
                                                <button class='btn-close float-end' type='button' data-bs-dismiss='modal' aria-label='Close'></button>
                                                <h5 class='modal-title text-center' id='exampleModalCenterTitle'>Removal Confirmation</h5>
                                            </div>
                                            <div class='modal-body text-center'>
                                                Do you really want to delete this client ?
                                            </div>
                                            <div class='modal-footer justify-content-center'>
                                                <a class='btn btn-secondary' type='button' data-bs-dismiss='modal'>No</a>
                                                <a class='btn btn-success' type='button' href='$deleteClientLink'>Yes</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                ";
                            };
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script>
    $( document ).ready(function() {
        const datatablesSimple = document.getElementById('datatablesSimple');
        if (datatablesSimple) {
            new simpleDatatables.DataTable(datatablesSimple, {
                /*sortable: false,*/
                columns: [
                    { select: [1,6,7], sortable: true },
                    { select: [0,2,3,4,5,8], sortable: false },
                ]
            });
        }
        let clientsArray = [];
        $("#importClientButton").click(function () {
            $("#buttonsContainer").hide()
            $("#formContainer").show()
        })
        $("#backButton").click(function () {
            $("#formContainer").hide()
            $("#buttonsContainer").show()

        })
        $(".checkAll").click(function () {
            $("input[type=checkbox]").prop('checked', $(this).prop('checked'));
            if($(this).prop('checked') == true)
            {
                $('input[type=checkbox][class!=checkAll]:checked').each(function(){
                    clientsArray.push($(this).val())
                });
            } else {
                clientsArray = [];
            }
        });
        $(document).on('change', 'input[type=checkbox]', function() {
            /*$('th, td').css({"text-align": "center", "vertical-align": "middle"})*/
            if($("input[type=checkbox]").length == 1) return;
            if($("input[type=checkbox]:checked").length > 0)
            {
                $("#sendInviteButton").prop("disabled", false)
                $("#trashButton").prop("disabled", false)
            } else {
                $("#sendInviteButton").prop("disabled", true)
                $("#trashButton").prop("disabled", true)
            }
            if($(this).prop('checked') == true)
            {
                if($(this).val() != "on")
                {
                    clientsArray.push($(this).val())
                }
            } else if($(this).prop('checked') == false)
            {
                const removeFromArray = function (arr, ...theArgs) {
                    return arr.filter( val => !theArgs.includes(val) )
                };
                clientsArray = removeFromArray(clientsArray, $(this).val());
            }
        });

        /*$("#emailInvitaionForm").submit(function (e) {
            $(".selected_clients").val(JSON.stringify(clientsArray))
        })*/
        $("#sendInviteButton").click(function (e) {
            e.preventDefault();
            $(".selected_clients").val(JSON.stringify(clientsArray))
            $('#selectedClientsForm').attr('action', "/clients/send-invitation-to-client").submit();
        })
        $("#trashButton").click(function (e) {
            e.preventDefault();
            $(".selected_clients").val(JSON.stringify(clientsArray))
            $('#selectedClientsForm').attr('action', "/clients/custom-delete").submit();
        })

    });
</script>
</body>
</html>
