<?php
/* @var $story
 * @var $id
 * @var $image
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Edit Story</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="edit"></i></div>
                                    Edit Story
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form id="editBlogForm" action="/stories/edit?id=<?=$id?>" method="post" enctype="multipart/form-data">
                    <div class="row gx-4 mb-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-3">
                            <div class="card card-header-actions mb-4 mb-lg-0">
                                <div class="card-header">
                                    Image
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body">
                                    <div class="mb-3">
                                        <img src='<?=$image?>' alt='no-image-available' height='150px' width='200px'>
                                    </div>
                                    <input type="file" accept="image/jpeg/png" name="image">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card mb-4">
                                <div class="card-header">Category</div>
                                <div class="card-body">
                                    <select class="form-control" id="category" name="category" required>
                                        <option value="">Select Category</option>
                                        <option value="Real Estate">Real Estate</option>
                                        <option value="Lifestyle">Lifestyle</option>
                                        <option value="DIY projects">DIY projects</option>
                                        <option value="News">News</option>
                                        <option value="Seasonal">Seasonal</option>
                                        <option value="Personal">Personal</option>
                                        <option value="Miscellaneous">Miscellaneous</option>
                                        <option value="Monthly posts">Monthly posts</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card mb-4">
                                <div class="card-header">Title</div>
                                <div class="card-body"><input class="form-control" id="postTitleInput" type="text" value="<?=$story["title"]?>" name="title" required/></div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>
                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-10">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">
                                    Content
                                    <i class="text-muted" title="The post preview text shows below the post title, and is the post summary on blog pages."></i>
                                </div>
                                <div class="card-body"><textarea id="postDistribution" class="lh-base form-control" type="text" rows="10" style="resize: none" name="content"></textarea></div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>

                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-10">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">Embed Video</div>
                                <div class="card-body">
                                    <textarea id="embedded-video" class="lh-base form-control" type="text" placeholder="Enter your video embedded code..." rows="3" name="embedded-video" style="resize: none"><?php if(isset($story["embedded_video"]) && $story["embedded_video"] !== "") echo $story["embedded_video"]; ?></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>
                    <div class="text-center">
                        <div><input class="fw-500 btn btn-primary" type="submit" value="Save"></div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script src="https://unpkg.com/turndown/dist/turndown.js"></script>
<script>
    $(document).ready(function() {
        const easyMDE = new EasyMDE({
            element: document.getElementById('postDistribution')
        });
        const turndownService = new TurndownService()
        /*console.log(turndownService.turndown(easyMDE.value()))*/
        easyMDE.value(turndownService.turndown(<?php echo json_encode($story["distribution"]);  ?>));
        $("#editBlogForm").submit(function (e) {
            let postContent = $("#postDistribution").val()
            $("#postDistribution").val(marked.parse(postContent))
        })
        <?php
        if(isset($story["category"]))
        {?>
        let category = "<?php echo $story["category"]; ?>";
        $("#category").val(category);
        <?php
        }
        ?>
    });
</script>
</body>
</html>
