<?php
/* @var $stories
 * @var $realtor
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>My Stories</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="list"></i></div>
                                    My Stories
                                </h1>
                            </div>
                            <div class="col mb-3">
                                <form id="publishStoryForm" action="/stories/publish" method="post">
                                    <input type="hidden" id="selected_stories" name="selectedStories">
                                    <button type="submit" id="publishStoryButton" class="btn btn-sm btn-light text-primary" href="#" disabled>
                                        <i class="me-1" data-feather="send"></i>
                                        Publish story
                                    </button>
                                </form>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/new">
                                    <i class="me-1" data-feather="plus"></i>
                                    Create New Story
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <?php
                if(isset($successFlashMessage))
                {
                    echo "<div class='alert alert-success' role='alert'>$successFlashMessage</div>";
                }
                ?>
                <div class="card">
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th class='text-center' style='vertical-align: middle; max-width: 10px'><input type='checkbox' class="checkAll"></th>
                                <th class='text-center' style='vertical-align: middle'>Story Title</th>
                                <th class='text-center' style='vertical-align: middle'>Created At</th>
                                <th class='text-center' style='vertical-align: middle'>Published At</th>
                                <th class='text-center' style='vertical-align: middle'>Views</th>
                                <th class='text-center' style='vertical-align: middle'>Likes</th>
                                <th class='text-center' style='vertical-align: middle'>Actions</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th><input type='checkbox' class="checkAll"></th>
                                <th>Story Title</th>
                                <th>Created At</th>
                                <th>Published At</th>
                                <th>Views</th>
                                <th>Likes</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            foreach ($stories as $story)
                            {
                                $id = $story->doc_id;
                                $title = $story->title;
                                $content = $story->distribution;
                                $image = isset($story->img) && trim($story->img) !== '' && file_exists($_SERVER["DOCUMENT_ROOT"] . $story->img) ? $this->baseUri . $story->img : $this->noImagePath;
                                $createdAt = $story->date->get()->format("m-d-Y");
                                $views = $story->views ?? 0;
                                if(isset($story->user_liked)) {
                                    $likes = count($story->user_liked);
                                } else {
                                    $likes = 0;
                                }
                                $publishedAt = isset($story->published_at) && trim($story->published_at) !== "" ? $story->published_at->get()->format("m-d-Y") : "";
                                $showStoryLink = "show?id=$id";
                                $editStoryLink = "edit?id=$id";
                                $deleteStoryLink = "delete?id=$id";
                                echo "
                                <tr>
                                    <td class='text-center' style='vertical-align: middle'><input type='checkbox' value=$id></td>
                                    <td class='text-center' style='vertical-align: middle'>$title</td>
                                    <td class='text-center' style='min-width: 70px; vertical-align: middle'>$createdAt</td>
                                    <td class='text-center' style='min-width: 70px; vertical-align: middle'>$publishedAt</td>
                                    <td class='text-center' style='vertical-align: middle'>$views</td>
                                    <td class='text-center' style='vertical-align: middle'>$likes</td>
                                    <td class='text-center'>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' data-bs-toggle='modal' data-bs-target='#previewStoryModal$id'><i data-feather='eye'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$showStoryLink><i data-feather='zoom-in'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$editStoryLink><i data-feather='edit'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark' data-bs-toggle='modal' data-bs-target='#approveUserModal$id'><i data-feather='trash-2'></i></a>                                                                                                                              
                                    </td>                                                      
                                </tr>
                                
                                <!-- Modal Preview Story-->
                                <div class='modal fade' id='previewStoryModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalScrollableTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-scrollable' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-body mt-3'>
                                                <div class='text-center mb-3'>
                                                    <img src='$image' alt='no-image-available' height='200px' width='300px'>
                                                </div>
                                                <div class='text-center mb-3'>
                                                    <h3>$title</h3>
                                                </div>
                                                <div>
                                                    $content
                                                </div>
                                            </div>
                                            <div class='text-center mb-3'>
                                            <button class='btn' style='background-color: #00b386; color: white; border-radius: 20px' type='button' data-bs-dismiss='modal'>Close</button>
                                            </div>
                                            <!--<div class='modal-footer'>
                                                
                                            </div>-->
                                        </div>
                                    </div>
                                </div>
                                
                                <!-- Modal Delete Story-->
                                <div class='modal fade' id='approveUserModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalCenterTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-centered' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-header d-block'>
                                                <button class='btn-close float-end' type='button' data-bs-dismiss='modal' aria-label='Close'></button>
                                                <h5 class='modal-title text-center' id='exampleModalCenterTitle'>Removal Confirmation</h5>
                                            </div>
                                            <div class='modal-body text-center'>
                                                Do you really want to delete this story ?
                                            </div>
                                            <div class='modal-footer justify-content-center'>
                                                <a class='btn btn-secondary' type='button' data-bs-dismiss='modal'>No</a>
                                                <a class='btn btn-success' type='button' href='$deleteStoryLink'>Yes</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                ";
                            };
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script>
    $( document ).ready(function() {
        let storiesArray = [];
        $(".checkAll").click(function () {
            $("input[type=checkbox]").prop('checked', $(this).prop('checked'));
            if($(this).prop('checked') == true)
            {
                $('input[type=checkbox][class!=checkAll]:checked').each(function(){
                    storiesArray.push($(this).val())
                });
            } else {
                storiesArray = [];
            }
        });
        $(document).on('change', 'input[type=checkbox]', function() {
            if($("input[type=checkbox]").length == 1) return;
            if($("input[type=checkbox]:checked").length > 0)
            {
                $("#publishStoryButton").prop("disabled", false)
            } else {
                $("#publishStoryButton").prop("disabled", true)
            }
            if($(this).prop('checked') == true)
            {
                if($(this).val() != "on")
                {
                    storiesArray.push($(this).val())
                }
            } else if($(this).prop('checked') == false)
            {
                const removeFromArray = function (arr, ...theArgs) {
                    return arr.filter( val => !theArgs.includes(val) )
                };
                storiesArray = removeFromArray(storiesArray, $(this).val());
            }
        });

        $("#publishStoryForm").submit(function (e) {
            $("#selected_stories").val(JSON.stringify(storiesArray))
        })
    });
</script>
</body>
</html>
