<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Create Story</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="plus"></i></div>
                                    Create Story
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form id="addBlogForm" action="/stories/new-save" method="post" enctype="multipart/form-data">
                    <div class="row gx-4">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-3">
                            <div class="card card-header-actions mb-4 mb-lg-0">
                                <div class="card-header">
                                    Image
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body mt-3">
                                    <input type="file" accept="image/jpeg/png" name="image">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div class="card mb-4">
                                <div class="card-header">Title</div>
                                <div class="card-body"><input class="form-control" id="postTitleInput" type="text" placeholder="Enter your story title..." name="title" required/></div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                        </div>
                    </div>
                    <div class="row gx-4">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-8">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">
                                    Content
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body"><textarea id="postDistribution" class="lh-base form-control" type="text" placeholder="Enter your story content text..." rows="10" name="content"></textarea></div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                        </div>
                    </div>
                    <div class="text-center">
                        <div><input class="fw-500 btn btn-primary" type="submit" value="Save"></div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="../../../public/js/markdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    $("#addBlogForm").submit(function (e) {
        let postContent = $("#postDistribution").val()
        $("#postDistribution").val(marked.parse(postContent))
        console.log($("#postDistribution").val())
    })
</script>
</body>
</html>
