<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Custom Story</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="plus"></i></div>
                                    Custom Story
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-4">
                <nav class="nav nav-borders">
                    <a class="nav-link active ms-0" href="/stories/new">Custom Story</a>
                    <a class="nav-link" href="/stories/story-link/new">Share a Link</a>
                </nav>
                <hr class="mt-0 mb-4" />
                <form id="addBlogForm" action="/stories/new" method="post" enctype="multipart/form-data">
                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-3">
                            <div class="card mb-4">
                                <div class="card-header">Category</div>
                                <div class="card-body">
                                    <select class="form-control" id="category" name="category" required>
                                        <option value="">Select Category</option>
                                        <option value="Real Estate">Real Estate</option>
                                        <option value="Lifestyle">Lifestyle</option>
                                        <option value="DIY projects">DIY projects</option>
                                        <option value="News">News</option>
                                        <option value="Seasonal">Seasonal</option>
                                        <option value="Personal">Personal</option>
                                        <option value="Miscellaneous">Miscellaneous</option>
                                        <option value="Monthly posts">Monthly posts</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card card-header-actions mb-4 mb-lg-0">
                                <div class="card-header">
                                    Image
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body mt-3">
                                    <input type="file" accept="image/jpeg/png" name="image">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card mb-4">
                                <div class="card-header">Title</div>
                                <div class="card-body"><input class="form-control" id="postTitleInput" type="text" placeholder="Enter your story title..." name="title" required/></div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>
                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-10">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">
                                    Content
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body"><textarea id="postDistribution" class="lh-base form-control" type="text" placeholder="Enter your story content text..." rows="10" name="content"></textarea></div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>

                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-10">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">Embed Video</div>
                                <div class="card-body">
                                    <textarea id="embedded-video" class="lh-base form-control" type="text" placeholder="Enter your video embedded code..." rows="3" name="embedded-video" style="resize: none"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>

                    <div class="text-center">
                        <div><input class="fw-500 btn btn-primary" type="submit" value="Save"></div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="../../../public/js/markdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    $(document).ready(function() {
        $("#addBlogForm").submit(function (e) {
            let postContent = $("#postDistribution").val()
            $("#postDistribution").val(marked.parse(postContent))
        })
        //
        /*$("body").on("click",".add-new-row-btn", function (e) {
            e.preventDefault()
            let index = $(".articles").find(".articles-row").length + 1;
            console.log(index);
            $(".add-new-row-btn").before(`
            <div class="input-group mt-2 articles-row">
                <input class="form-control align-middle" type="text" placeholder="Link..." name="articles[]" required>
                <span class="align-middle ms-2">
                    <button class="btn_round remove-row-btn">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </span>
            </div>
            `);
            //===== delete the form field row
            $("body").on("click", ".remove-row-btn", function () {
                $(this).closest(".articles-row").remove();
                console.log("success");
            });
        });*/
    })
</script>
</body>
</html>
