<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Create Story</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="plus"></i></div>
                                    Create Story
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form id="addBlogForm" action="/stories/new-save" method="post" enctype="multipart/form-data">
                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-3">
                            <div class="card card-header-actions mb-4 mb-lg-0">
                                <div class="card-header">
                                    Image
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body mt-3">
                                    <input type="file" accept="image/jpeg/png" name="image">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card mb-4">
                                <div class="card-header">Category</div>
                                <div class="card-body">
                                    <select class="form-control" id="category" name="category" required>
                                        <option>Select Category</option>
                                        <option value="Real Estate">Real Estate</option>
                                        <option value="Lifestyle">Lifestyle</option>
                                        <option value="DIY projects">DIY projects</option>
                                        <option value="News">News</option>
                                        <option value="Seasonal">Seasonal</option>
                                        <option value="Personal">Personal</option>
                                        <option value="Miscellaneous">Miscellaneous</option>
                                        <option value="Monthly posts">Monthly posts</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="card mb-4">
                                <div class="card-header">Title</div>
                                <div class="card-body"><input class="form-control" id="postTitleInput" type="text" placeholder="Enter your story title..." name="title" required/></div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>
                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-10">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">
                                    Content
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body"><textarea id="postDistribution" class="lh-base form-control" type="text" placeholder="Enter your story content text..." rows="10" name="content"></textarea></div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>
                    <div class="row gx-4">
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-10">
                            <div class="card card-header-actions mb-4">
                                <div class="card-header">
                                    Articles
                                    <i class="text-muted"></i>
                                </div>
                                <div class="card-body embedded-videos">
                                    <!--<div class="input-group">
                                        <input class="form-control align-middle" type="text" placeholder="Video Link...">
                                        <span class="align-middle ms-2">
                                            <button class="btn_round remove_node_btn_frm_field">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </span>
                                    </div>-->
                                    <button class="mt-2 py-3 border btn btn-outline-lite py-0 add-new-row-btn"><i class="fas fa-plus add_icon me-2"></i>New Row</button>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-1">
                        </div>
                    </div>
                    <div class="text-center">
                        <div><input class="fw-500 btn btn-primary" type="submit" value="Save"></div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="../../../public/js/markdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    $(document).ready(function() {
        $("#addBlogForm").submit(function (e) {
            let postContent = $("#postDistribution").val()
            $("#postDistribution").val(marked.parse(postContent))
            /*console.log($("#postDistribution").val())*/
        })
        //
        $("body").on("click",".add-new-row-btn", function (e) {
            e.preventDefault()
            console.log("clicked");
            let index = $(".embedded-videos").find(".embedded-videos-row").length + 1;
            console.log(index);
            $(".add-new-row-btn").before(`
            <div class="input-group mt-2 embedded-videos-row">
                <input class="form-control align-middle" type="text" placeholder="Link..." required>
                <span class="align-middle ms-2">
                    <button class="btn_round remove-row-btn">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </span>
            </div>
            `);
            /*$(".embedded-videos").find(".remove_node_btn_frm_field:not(:first)").prop("disabled", false);
            $(".form_field_outer").find(".remove_node_btn_frm_field").first().prop("disabled", true); */
            //===== delete the form fieed row
            $("body").on("click", ".remove-row-btn", function () {
                $(this).closest(".embedded-videos-row").remove();
                console.log("success");
            });
        });
    })
</script>
</body>
</html>
