<?php
/* @var $story */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Story Details</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="zoom-in"></i></div>
                                    Story Details
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="row gx-4">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        <div class="card mb-4">
                            <div class="card-header">Story Title</div>
                            <div class="card-body"><input class="form-control" id="postTitleInput" type="text" value="<?=$story["title"]?>" disabled/></div>
                        </div>
                        <div class="card card-header-actions mb-4">
                            <div class="card-header">
                                Story Content
                                <i class="text-muted" title="The post preview text shows below the post title, and is the post summary on blog pages."></i>
                            </div>
                            <div class="card-body"><textarea id="postDistributionShow" class="lh-base form-control" type="text" rows="10" style="resize: none" disabled><?=$story["distribution"]?></textarea></div>
                        </div>
                        <div class="card card-header-actions mb-4 mb-lg-0">
                            <div class="card-header">
                                Story Image
                                <i class="text-muted" title="Markdown is supported within the post content editor."></i>
                            </div>
                            <div class="card-body">
                                <?php
                                $image = $story["img"];
                                if(isset($image) && trim($image) !== "")
                                    echo "<img src='$image' alt='' height='150px' width='200px'>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    const easyMDE = new EasyMDE({
        element: document.getElementById('postDistributionShow'),
        toolbar: false
    });
    easyMDE.markdown(easyMDE.value());
    easyMDE.togglePreview();
</script>
</body>
</html>
