<?php
/* @var $story
 * @var $image
 * @var $articles
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Story Details</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="zoom-in"></i></div>
                                    Story Details
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="row gx-4 mb-4">
                    <div class="col-lg-1">
                    </div>
                    <div class="col-lg-3">
                        <div class="card card-header-actions mb-4 mb-lg-0">
                            <div class="card-header">
                                Image
                                <i class="text-muted" title="Markdown is supported within the post content editor."></i>
                            </div>
                            <div class="card-body">
                                <img src='<?=$image?>' alt='no-image-available' height='150px' width='200px'>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="card mb-4">
                            <div class="card-header">Category</div>
                            <div class="card-body"><input class="form-control" id="postCategoryInput" type="text" value="<?php if(isset($story["category"])) { echo $story["category"];} else {echo 'N/A'; }?>" disabled/></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="card mb-4">
                            <div class="card-header">Title</div>
                            <div class="card-body"><input class="form-control" id="postTitleInput" type="text" value="<?=$story["title"]?>" disabled/></div>
                        </div>
                    </div>
                    <div class="col-lg-1">
                    </div>
                </div>
                <div class="row gx-4">
                    <div class="col-lg-1">
                    </div>
                    <div class="col-lg-10">
                        <div class="card card-header-actions mb-4">
                            <div class="card-header">
                                Content
                                <i class="text-muted" title="The post preview text shows below the post title, and is the post summary on blog pages."></i>
                            </div>
                            <div class="card-body"><textarea id="postDistributionShow" class="lh-base form-control" type="text" rows="10" style="resize: none" disabled><?=$story["distribution"]?></textarea></div>
                        </div>
                    </div>
                    <div class="col-lg-1">
                    </div>
                </div>

                    <div class="row gx-4">
                        <?php
                        foreach ($articles as $index => $article)
                        {
                        ?>
                            <div class="col-lg-4">
                                <div class="card card-header-actions mb-4">
                                    <div class="card-header">
                                        Article <?=$index + 1 ?>
                                        <i class="text-muted"></i>
                                    </div>
                                    <div class="card-body embedded-videos">
                                        <a href="<?=$article->url?>" target="_blank" style="text-decoration: none; color: inherit">
                                            <img id="my-image" src="<?=$article->image?>" class="img-fluid" height="150" alt="image-preview">
                                            <div>
                                                <div id="my-title" class="fw-bolder">
                                                    <?=$article->title?>
                                                </div>
                                                <div id="my-description" class="mt-2">
                                                    <?=$article->description?>
                                                </div>
                                                <div id="my-url" class="mt-2">
                                                    <?=$article->site_name?>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        <?php
                        }
                        ?>
                    </div>

            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    $(document).ready(function() {
        const easyMDE = new EasyMDE({
            element: document.getElementById('postDistributionShow'),
            toolbar: false
        });
        easyMDE.markdown(easyMDE.value());
        easyMDE.togglePreview();
        //

    })
</script>
</body>
</html>
