<?php
/* @var $invitationEmail */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Invitation Email</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="edit"></i></div>
                                    Edit Invitation Email
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form action="/admin/emails/invitation" method="post">
                    <div class="row gx-4">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-8">
                            <div class="card mb-4 text-center">
                                <div class="card-header">
                                    Subject
                                </div>
                                <div class="card-body"><input class="form-control" id="postTitleInput" type="text" placeholder="Enter your email subject here..." value="<?=$invitationEmail["subject"]?>" name="emailSubject" required/></div>
                            </div>
                            <div class="card mb-4 text-center">
                                <div class="card-header">
                                    Content
                                </div>
                                <div class="card-body"><textarea class="lh-base form-control" type="text" placeholder="Enter your email content here..." rows="25" name="emailContent" style="resize: none" required><?=$invitationEmail["content"]?></textarea></div>
                            </div>
                            <div class="text-center">
                                <div class="card-body">
                                    <div><input class="btn btn-primary" type="submit" value="Save"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
</body>
</html>
