<?php
/* @var $client */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Client Details</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="zoom-in"></i></div>
                                    Client Details
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/admin/clients/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to Clients List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-sm px-4">
                <h6 class="heading-small text-blue mb-3">Client 1</h6>
                <div class="pl-lg-4">
                    <div class="row mb-5">
                        <div class="col-md-3">
                            <label class="small mb-1" for="firstName1">First name</label>
                            <input class="form-control" id="firstName1" type="text" value="<?=$client["first_name_1"]?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label class="small mb-1" for="lastName1">Last name</label>
                            <input class="form-control" id="lastName1" type="text" value="<?=$client["last_name_1"]?>" disabled/>
                        </div>

                        <div class="col-md-3">
                            <label class="small mb-1" for="email1">Email</label>
                            <input class="form-control" id="email1" type="text" value="<?=$client["email_1"]?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label class="small mb-1" for="phoneNumber1">Phone Number</label>
                            <input class="form-control" id="phoneNumber1" type="text" value="<?=$client["phone_1"]?>" disabled/>
                        </div>
                    </div>
                </div>

                <h6 class="heading-small text-blue mb-3">Client 2</h6>
                <div class="pl-lg-4">
                    <div class="row mb-5">
                        <div class="col-md-3">
                            <label class="small mb-1" for="firstName2">First name</label>
                            <input class="form-control" id="firstName2" type="text" value="<?=$client["first_name_2"]?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label class="small mb-1" for="lastName2">Last name</label>
                            <input class="form-control" id="lastName2" type="text" value="<?=$client["last_name_2"]?>" disabled/>
                        </div>

                        <div class="col-md-3">
                            <label class="small mb-1" for="email2">Email</label>
                            <input class="form-control" id="email2" type="text" value="<?=$client["email_2"]?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label class="small mb-1" for="phoneNumber2">Phone Number</label>
                            <input class="form-control" id="phoneNumber2" type="text" value="<?=$client["phone_2"]?>" disabled/>
                        </div>
                    </div>
                </div>

                <h6 class="heading-small text-blue mb-3">Home Detail</h6>
                <div class="pl-lg-4">
                    <div class="row mb-5">
                        <div class="col-md-4">
                            <label class="small mb-1" for="address1">Address 1</label>
                            <input class="form-control" id="address1" type="text" value="<?=$client["address_1"]?>" disabled/>
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1" for="address2">Address 2</label>
                            <input class="form-control" id="address2" type="text" value="<?=$client["address_2"]?>" disabled/>
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1" for="state">State</label>
                            <input class="form-control" id="state" type="text" value="<?=$client["state"]?>" disabled/>
                        </div>
                    </div>

                    <div class="row mb-5">
                        <div class="col-md-4">
                            <label class="small mb-1" for="city">City</label>
                            <input class="form-control" id="city" type="text" value="<?=$client["city"]?>" disabled/>
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1" for="zipCode">Zip Code</label>
                            <input class="form-control" id="zipCode" type="text" value="<?=$client["zip"]?>" disabled/>
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1" for="homeType">Home Type</label>
                            <input class="form-control" id="homeType" type="text" value="<?=$client["home_type"]?>" disabled/>
                        </div>
                    </div>
                </div>
                <h6 class="heading-small text-blue mb-3">Personal Notes/Reminders</h6>
                <div class="pl-lg-4">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <label class="small mb-1" for="notes">Notes</label>
                            <textarea class="lh-base form-control" type="text" rows="5" style="resize: none" disabled><?=$client["notes"]?></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
</body>
</html>
