<?php
/* @var $proServices
 * @var $realtor
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>My Pro Services</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="list"></i></div>
                                    My Pro Services
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <div id="formContainer" style="display: none">
                                    <form action="/pro-services/import" method="post" enctype="multipart/form-data">
                                        <input id="excelHomeProsfile" type="file" name="excelHomeProsfile" class="form-control-sm" style="width: 210px" accept=".csv,.ods, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" required>
                                        <input class="btn btn-sm btn-success" type="submit" name="submit" value="Confirm">
                                        <a id="backButton" class="btn btn-sm btn-secondary">Back</a>
                                    </form>
                                </div>
                                <div id="buttonsContainer">
                                    <a data-bs-toggle=tooltip data-bs-placement=left title='Export to CSV' href="/pro-services/export-to-csv"><i class="fa-solid fa-file-export"></i></a>
                                    <a class="btn btn-sm btn-light text-primary" href="/pro-services/template-download">
                                        <i class="me-1" data-feather="download"></i>
                                        Download Pro Services Template
                                    </a>
                                    <a class="btn btn-sm btn-light text-primary" href="/pro-services/new">
                                        <i class="me-1" data-feather="plus"></i>
                                        Create New Pro Service
                                    </a>
                                    <a id="importProServicesButton" class="btn btn-sm btn-light text-primary">
                                        <i class="me-1" data-feather="plus"></i>
                                        Import Pro Services
                                    </a>
                                </div>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="card">
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th>Company Name</th>
                                <th>Date Created</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Company Name</th>
                                <th>Date Created</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            foreach ($proServices as $proService)
                            {
                                $id = $proService->doc_id;
                                /*$content = $proService->distribution;*/
                                $companyName = $proService->company_name;
                                $companyEmail = $proService->company_email;
                                $companyWebsite = $proService->company_website_link;
                                $companyPhoneNumber = $proService->company_phone_number;
                                $image = isset($proService->img) && trim($proService->img) !== '' && file_exists($_SERVER["DOCUMENT_ROOT"] . $proService->img) ? $this->baseUri . $proService->img : $this->noImagePath;
                                $comments = $proService->comments;
                                $notes = $proService->my_notes;
                                $createdAt = $proService->date;
                                $createdAtFormatted = $createdAt->get()->format("m-d-Y");
                                $showProServiceLink = "show?id=$id";
                                $editProServiceLink = "edit?id=$id";
                                $deleteProServiceLink = "delete?id=$id";
                                echo "
                                <tr>
                                    <td>$companyName</td>
                                    <td>$createdAtFormatted</td>
                                    <td class='text-center'>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' data-bs-toggle='modal' data-bs-target='#previewHdProsModal$id'><i data-feather='eye'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$showProServiceLink><i data-feather='zoom-in'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$editProServiceLink><i data-feather='edit'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark' data-bs-toggle='modal' data-bs-target='#approveUserModal$id'><i data-feather='trash-2'></i></a>                                                                                                                              
                                    </td>                                                                                          
                                </tr>
                                
                                <!-- Modal Preview HD PROS-->
                                <div class='modal fade' id='previewHdProsModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalScrollableTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-scrollable' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-body'>
                                            <div>
                                                <h5 class='mb-0'>$companyName</h5>
                                                <span>$companyEmail</span><br>
                                                <a href='$companyWebsite' target='_blank'>$companyWebsite</a><br>
                                                <span class='mb-0'>$companyPhoneNumber</span>
                                                 <hr>
                                            </div>
                                                <div class='text-center mb-3'>
                                                    <img src='$image' alt='no-image-available' height='200px' width='300px'>
                                                </div>
                                                <div class='mb-3'>
                                                    <h4>Comments (Public)</h4>
                                                </div>
                                                <p class='fw-bold'>
                                                    $comments
                                                </p>
                                                <p class='fw-bold'>
                                                    $notes
                                                </p>
                                                <hr>
                                            </div>
                                            <div class='text-center mb-3'>
                                            <button class='btn' style='background-color: #00b386; color: white; border-radius: 20px' type='button' data-bs-dismiss='modal'>Close</button>
                                            </div>
                                            <!--<div class='modal-footer'>
                                                
                                            </div>-->
                                        </div>
                                    </div>
                                </div>
                                
                                
                                 <!-- Modal Delete HD PROS-->
                                <div class='modal fade' id='approveUserModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalCenterTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-centered' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-header d-block'>
                                                <button class='btn-close float-end' type='button' data-bs-dismiss='modal' aria-label='Close'></button>
                                                <h5 class='modal-title text-center' id='exampleModalCenterTitle'>Removal Confirmation</h5>
                                            </div>
                                            <div class='modal-body text-center'>
                                                Do you really want to delete this pro service ?
                                            </div>
                                            <div class='modal-footer justify-content-center'>
                                                <a class='btn btn-secondary' type='button' data-bs-dismiss='modal'>No</a>
                                                <a class='btn btn-success' type='button' href='$deleteProServiceLink'>Yes</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                ";
                            };
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script>
    $( document ).ready(function() {
        $("#importProServicesButton").click(function () {
            $("#buttonsContainer").hide()
            $("#formContainer").show()
        })
        $("#backButton").click(function () {
            $("#formContainer").hide()
            $("#buttonsContainer").show()
        })
    });
</script>
</body>
</html>
