<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Create Pro Service</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="plus"></i></div>
                                    Create Pro Service
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/pro-services/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Pro Services
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form action="/pro-services/new-save" method="post" enctype="multipart/form-data">
                    <div class="row gx-4">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-8">
                            <div class="row gx-4 align-items-center">
                                <div class="col-lg-8">
                                    <div class="card mb-4">
                                        <div class="card-header">My Notes</div>
                                        <div class="card-body"><textarea class="lh-base form-control" type="text" placeholder="Enter your notes..." style="resize: none" rows="5" name="myNotes" required></textarea></div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="card">
                                        <div class="card-header">Home Pro Type</div>
                                        <div class="card-body">
                                            <select class="form-control" id="homeProType" name="homeProType" required>
                                                <option>Select Home Pro Type</option>
                                                <option value="Cleaning">Cleaning</option>
                                                <option value="Electrical">Electrical</option>
                                                <option value="Fencing">Fencing</option>
                                                <option value="Handy person">Handy person</option>
                                                <option value="Home Renovation">Home Renovation</option>
                                                <option value="HVAC">HVAC</option>
                                                <option value="Inspector">Inspector</option>
                                                <option value="Lawncare">Lawncare</option>
                                                <option value="Painting">Painting</option>
                                                <option value="Pest Control">Pest Control</option>
                                                <option value="Plumbing">Plumbing</option>
                                                <option value="Power Washing">Power Washing</option>
                                                <option value="Roofing">Roofing</option>
                                                <option value="Security System">Security System</option>
                                                <option value="Windows">Windows</option>
                                                <option value="Other">Other</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row gx-4">
                                <div class="col-lg">
                                    <div class="card mb-4">
                                        <div class="card-header">Company Name</div>
                                        <div class="card-body"><input class="form-control" id="proServiceTitleInput" type="text" placeholder="Enter company name..." name="companyName" required/></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row gx-4">
                                <div class="col-lg-6">
                                    <div class="card mb-4">
                                        <div class="card-header">Company Email</div>
                                        <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" placeholder="Enter company email..." name="companyEmail" required/></div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="card mb-4">
                                        <div class="card-header">Company Phone Number</div>
                                        <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" placeholder="Enter company phone number..." name="companyPhoneNumber" required/></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row gx-4">
                                <div class="col-lg">
                                    <div class="card mb-4">
                                        <div class="card-header">Company Website Link</div>
                                        <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" placeholder="Enter company website link..." name="companyWebsiteLink" required/></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row gx-4 align-items-center">
                                <div class="col-lg-8">
                                    <div class="card mb-4">
                                        <div class="card-header">Comments</div>
                                        <div class="card-body"><textarea class="lh-base form-control" type="text" placeholder="Enter your comments..." style="resize: none" rows="5" name="comments" required></textarea></div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="card mb-4">
                                        <div class="card-header">Image</div>
                                        <div class="card-body"><input type="file" accept="image/jpeg/png" name="image"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                        </div>
                    </div>
                    <div class="text-center">
                        <div><input class="fw-500 btn btn-primary" type="submit" value="Save"></div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
</body>
</html>
