<?php
/* @var $proService
 * @var $image
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Pro Service Details</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="zoom-in"></i></div>
                                    Pro Service Details
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/pro-services/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Pro Services
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="row gx-4">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        <div class="row gx-4">
                            <div class="col-lg-8">
                                <div class="card mb-4">
                                    <div class="card-header">My Notes</div>
                                    <div class="card-body"><textarea class="lh-base form-control" type="text" style="resize: none" rows="5" disabled><?=$proService["my_notes"] ?? ""?></textarea></div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card mb-4">
                                    <div class="card-header">Home Pro Type</div>
                                    <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" value="<?=$proService["homePro_type"] ?? ""?>" disabled/></div>
                                </div>
                            </div>
                        </div>
                        <div class="row gx-4">
                            <div class="col-lg">
                                <div class="card mb-4">
                                    <div class="card-header">Company Name</div>
                                    <div class="card-body"><input class="form-control" id="proServiceTitleInput" type="text" value="<?= $proService["company_name"] ?? ""?>" disabled/></div>
                                </div>
                            </div>
                        </div>
                        <div class="row gx-4">
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    <div class="card-header">Company Email</div>
                                    <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" value="<?=$proService["company_email"] ?? ""?>" disabled/></div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    <div class="card-header">Company Phone Number</div>
                                    <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" value="<?=$proService["company_phone_number"] ?? ""?>" disabled/></div>
                                </div>
                            </div>
                        </div>
                        <div class="row gx-4">
                            <div class="col-lg">
                                <div class="card mb-4">
                                    <div class="card-header">Company Website Link</div>
                                    <div class="card-body"><input class="form-control" id="proServiceSubTitleInput" type="text" value="<?=$proService["company_website_link"] ?? ""?>" disabled/></div>
                                </div>
                            </div>
                        </div>
                        <div class="row gx-4">
                            <div class="col-lg-8">
                                <div class="card mb-4">
                                    <div class="card-header">Comments</div>
                                    <div class="card-body"><textarea class="lh-base form-control" type="text" style="resize: none" rows="6" disabled><?=$proService["comments"] ?? ""?></textarea></div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card mb-4">
                                    <div class="card-header">Image</div>
                                    <div class="card-body">
                                        <img src='<?=$image?>' alt='no-image-available' height='150px' width='200px'>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
</body>
</html>
