<?php
/* @var $realtor
 * @var $id
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Edit Realtor</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="edit"></i></div>
                                    Edit Realtor
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/admin/realtors/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to Realtors List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form action="/admin/realtors/edit?id=<?=$id?>" method="post">
                    <div class="row gx-4">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-8">
                            <div class="card mb-4">
                                <div class="card-header">Full name</div>
                                <div class="card-body"><input class="form-control" type="text" name="fullName" placeholder="Enter full name" value="<?=$realtor["realtor_title"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Email</div>
                                <div class="card-body"><input class="form-control" type="text" name="email" placeholder="Enter email" value="<?=$realtor["email"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Company</div>
                                <div class="card-body"><input class="form-control" type="text" name="companyName" placeholder="Enter company name" value="<?=$realtor["realtor_sub_title"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Phone Number</div>
                                <div class="card-body"><input class="form-control" type="text" name="phoneNumber" placeholder="Enter phone number" value="<?=$realtor["phone_number"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Address Line 1</div>
                                <div class="card-body"><input class="form-control" type="text" name="address1" placeholder="Enter address line 1" value="<?=$realtor["address_line_1"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Address Line 2</div>
                                <div class="card-body"><input class="form-control" type="text" name="address2" placeholder="Enter address line 2" value="<?=$realtor["address_line_2"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">City</div>
                                <div class="card-body"><input class="form-control" type="text" name="city" placeholder="Enter city" value="<?=$realtor["city"]?>"/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Zip Code</div>
                                <div class="card-body"><input class="form-control" type="text" name="zipCode" placeholder="Enter zip code" value="<?=$realtor["zip_code"]?>"/></div>
                            </div>
                            <div class="text-center">
                                <input class="fw-500 btn btn-primary" type="submit" value="Save">
                            </div>
                        </div>
                        <div class="col-lg-2">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
</body>
</html>
