<?php
/* @var $emailErrorMessage
 * @var $passwordErrorMessage
 * @var $confirmPasswordErrorMessage
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Create New Realtor</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white">
                <div class="container-fluid">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="plus"></i></div>
                                    Create New Realtor
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/admin/realtors/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to Realtors List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <form action="/admin/realtors/new" method="post">

                    <div class="row gx-4">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-8">
                            <div class="card mb-4">
                                <div class="card-header">Email</div>
                                <div class="card-body">
                                    <input class="form-control" type="text" name="email" placeholder="Enter email" required/>
                                    <?php
                                    if(isset($emailErrorMessage))
                                    {
                                        echo "<div class='text-sm text-red mt-2'>$emailErrorMessage</div>";
                                    }
                                    ?>
                                </div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Password</div>
                                <div class="card-body">
                                    <input class="form-control" type="password" name="password" placeholder="Enter password" required/>
                                    <div style="color: grey; font-size: small">
                                        <small>Password must be at least 8 characters long and contains a special character, e.g. !#$@.,:;()</small>
                                    </div>
                                    <?php
                                    if(isset($passwordErrorMessage))
                                    {
                                        echo "<div class='text-sm text-red mt-2'>$passwordErrorMessage</div>";
                                    }
                                    ?>
                                </div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Confirm Password</div>
                                <div class="card-body">
                                    <input class="form-control" type="password" name="confirmPassword" placeholder="Confirm password" required/>
                                    <?php
                                    if(isset($confirmPasswordErrorMessage))
                                    {
                                        echo "<div class='text-sm text-red mt-2'>$confirmPasswordErrorMessage</div>";
                                    }
                                    ?>
                                </div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Full name</div>
                                <div class="card-body"><input class="form-control" type="text" name="fullName" placeholder="Enter full name" required/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Company</div>
                                <div class="card-body"><input class="form-control" type="text" name="companyName" placeholder="Enter company name" required/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Phone Number</div>
                                <div class="card-body"><input class="form-control" type="text" name="phoneNumber" placeholder="Enter phone number" required/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Address Line 1</div>
                                <div class="card-body"><input class="form-control" type="text" name="address1" placeholder="Enter address line 1" required/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Address Line 2</div>
                                <div class="card-body"><input class="form-control" type="text" name="address2" placeholder="Enter address line 2" required/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">City</div>
                                <div class="card-body"><input class="form-control" type="text" name="city" placeholder="Enter city" required/></div>
                            </div>
                            <div class="card mb-4">
                                <div class="card-header">Zip Code</div>
                                <div class="card-body"><input class="form-control" type="text" name="zipCode" placeholder="Enter zip code" required/></div>
                            </div>
                            <div class="text-center">
                                <input class="fw-500 btn btn-primary" type="submit" value="Save">
                            </div>
                        </div>
                        <div class="col-lg-2">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
<script>
    $( document ).ready(function() {
        // Next Button
        // From Step 1 to Step 2
        $("#step1button").click(function () {
            $("#step1Form").hide()
            $("#progressbar1").hide()
            $("#step2Form").show()
            $("#progressbar2").show()
        })
        // From Step 2 to Step 3
        $("#step2button").click(function () {
            $("#step2Form").hide()
            $("#progressbar2").hide()
            $("#step3Form").show()
            $("#progressbar3").show()
        })
        // From Step 3 to Step 4
        $("#step3button").click(function () {
            $("#step3Form").hide()
            $("#progressbar3").hide()
            $("#step4Form").show()
            $("#progressbar4").show()
        })

        // Previous Button
        // From Step 1 to Step 2
        $("#step2prev").click(function () {
            $("#step2Form").hide()
            $("#progressbar2").hide()
            $("#step1Form").show()
            $("#progressbar1").show()
        })
        // From Step 2 to Step 3
        $("#step3prev").click(function () {
            $("#step3Form").hide()
            $("#progressbar3").hide()
            $("#step2Form").show()
            $("#progressbar2").show()
        })
        // From Step 3 to Step 4
        $("#step4prev").click(function () {
            $("#step4Form").hide()
            $("#progressbar4").hide()
            $("#step3Form").show()
            $("#progressbar3").show()
        })
    });
</script>
</body>
</html>
