<?php
/* @var $realtor */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Realtor Details</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="zoom-in"></i></div>
                                    Realtor Details
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/admin/realtors/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to Realtors List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="row gx-4">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        <div class="card mb-4">
                            <div class="card-header">Full name</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["realtor_title"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Email</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["email"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Company</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["realtor_sub_title"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Phone Number</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["phone_number"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Address Line 1</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["address_line_1"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Address Line 2</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["address_line_2"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">City</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["city"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Zip Code</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["zip_code"]?>" disabled/></div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">Created At</div>
                            <div class="card-body"><input class="form-control" type="text" value="<?=$realtor["date"]->get()->format("m-d-Y")?>" disabled/></div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
</body>
</html>
