<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Share a Link</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="plus"></i></div>
                                    Share a Link
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-4">
                <?php
                if (isset($failFlashMessage))
                {
                    echo "<div class='alert alert-danger' role='alert'>$failFlashMessage</div>";
                }
                ?>
                <nav class="nav nav-borders">
                    <a class="nav-link ms-0" href="/stories/new">Custom Story</a>
                    <a class="nav-link active" href="/stories/story-link/new">Share a Link</a>
                </nav>
                <hr class="mt-0 mb-4" />
                <form id="addBlogForm" action="/stories/story-link/new" method="post">
                    <div class="row gx-4">
                        <div class="col-lg-4">
                        </div>
                        <div class="col-lg-4">
                            <div class="card mb-4">
                                <div class="card-header">Category</div>
                                <div class="card-body">
                                    <select class="form-control" id="category" name="category" required>
                                        <option value="">Select Category</option>
                                        <option value="Real Estate">Real Estate</option>
                                        <option value="Lifestyle">Lifestyle</option>
                                        <option value="DIY projects">DIY projects</option>
                                        <option value="News">News</option>
                                        <option value="Seasonal">Seasonal</option>
                                        <option value="Personal">Personal</option>
                                        <option value="Miscellaneous">Miscellaneous</option>
                                        <option value="Monthly posts">Monthly posts</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                        </div>
                    </div>
                    <div class="row gx-4">
                        <div class="col-lg-3">
                        </div>
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <div class="card-header">Link</div>
                                <div class="card-body"><input class="form-control" id="postTitleInput" type="text" placeholder="Enter the link..." name="link" required/></div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                        </div>
                    </div>
                    <div class="text-center">
                        <div><input class="fw-500 btn btn-primary" type="submit" value="Save"></div>
                    </div>
                </form>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="../../../public/js/markdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    $(document).ready(function() {
        $("#addBlogForm").submit(function (e) {
            let postContent = $("#postDistribution").val()
            $("#postDistribution").val(marked.parse(postContent))
        })
    })
</script>
</body>
</html>
