<?php
/* @var $story
 * @var $image
 * @var $articles
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';?>
    <title>Story Link Preview</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="zoom-in"></i></div>
                                    Story Link Preview
                                </h1>
                            </div>
                            <div class="col-12 col-xl-auto mb-3">
                                <a class="btn btn-sm btn-light text-primary" href="/stories/list">
                                    <i class="me-1" data-feather="arrow-left"></i>
                                    Back to My Stories
                                </a>
                            <div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="row gx-4 mb-4">
                    <div class="col-lg-4">
                    </div>
                    <div class="col-lg-4">
                        <div class="card mb-4">
                            <div class="card-header text-center">Category</div>
                            <div class="card-body"><input class="form-control" id="postCategoryInput" type="text" value="<?php if(isset($story["category"])) { echo $story["category"];} else {echo 'N/A'; }?>" disabled/></div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                    </div>
                </div>
                <div class="row gx-4">
                    <div class="col-lg-4">
                    </div>
                    <div class="col-lg-4">
                        <div class="card mb-4">
                            <div class="card-header text-center">Link Preview</div>
                            <div class="card-body">
                                <a href="<?=$story['url']?>" target="_blank" style="text-decoration: none; color: inherit">
                                    <img id="my-image" src="<?=$story['img']?>" height="180" width="100%" alt="image-preview">
                                    <div>
                                        <div id="my-title" class="fw-bolder">
                                            <?=$story['title']?>
                                        </div>
                                        <div id="my-description" class="mt-2">
                                            <?=$story['description']?>
                                        </div>
                                        <div id="my-url" class="mt-2">
                                            <?=$story['site_name']?>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';?>
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    $(document).ready(function() {
        const easyMDE = new EasyMDE({
            element: document.getElementById('postDistributionShow'),
            toolbar: false
        });
        easyMDE.markdown(easyMDE.value());
        easyMDE.togglePreview();
        //
    })
</script>
</body>
</html>
