<div id="layoutSidenav_nav">
    <nav class="sidenav shadow-right sidenav-light">
        <div class="sidenav-menu">
            <div class="nav accordion" id="accordionSidenav">
                <!-- Sidenav Heading (Custom)-->
                <div class="sidenav-menu-heading">Dashboard</div>
                <!-- Sidenav Link (Blog Posts)-->
                <a class="nav-link" href="/stories/list">
                    <div class="nav-link-icon"><i data-feather="layout"></i></div>
                    My Stories
                </a>
                <!-- Sidenav Link (Pro Services)-->
                <a class="nav-link" href="/pro-services/list">
                    <div class="nav-link-icon"><i data-feather="tool"></i></div>
                    My Pro Services
                </a>
                <!-- Sidenav Link (Client)-->
                <a class="nav-link" href="/clients/list">
                    <div class="nav-link-icon"><i data-feather="users"></i></div>
                    My Clients
                </a>
            </div>
        </div>
    </nav>
</div>
