<?php
/* @var $portalClients
 * @var $this->user
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';?>
    <title>Portal Clients List</title>
</head>
<body class="nav-fixed">
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';?>
<div id="layoutSidenav">
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="list"></i></div>
                                    Portal Clients List
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4">
                <div class="card">
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                            <tr>
                                <th class='text-center' style='vertical-align: middle'>Realtor name<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='vertical-align: middle'>Client name<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='vertical-align: middle'>Address</th>
                                <th class='text-center' style='vertical-align: middle'>City<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='vertical-align: middle'>State<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='min-width: 120px; vertical-align: middle'>Created At<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='max-width: 70px; vertical-align: middle'>Email Invite Sent At<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class='text-center' style='max-width: 70px; vertical-align: middle'>Client Signed-up At<i class="fas fa-sort float-end mt-1"></i></th>
                                <th class="text-center" style='vertical-align: middle'>Actions</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Client name</th>
                                <th>Address</th>
                                <th>City</th>
                                <th>State</th>
                                <th>Date Created</th>
                                <th>Date Email Invite Sent</th>
                                <th>Date Client Signed-up</th>
                                <th>Actions</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            foreach ($portalClients as $client)
                            {
                                $realtor = $this->user->fetchUserById($client->realtor_id);
                                $realtorName = $realtor["realtor_title"] ?? "";
                                $clientName = $client->first_name_1 . " " . $client->last_name_1;
                                $address = $client->address_1;
                                $city = $client->city;
                                $state = $client->state;
                                if(isset($client->created_at)) {
                                    $createdAt = $client->created_at->get()->format("m-d-Y");
                                } else {
                                    $createdAt = "";
                                }
                                if(isset($client->email_invite_sent_at)) {
                                    $emailInviteSentDate = $client->email_invite_sent_at->get()->format("m-d-Y");
                                } else {
                                    $emailInviteSentDate = "";
                                }

                                if(isset($client->mobile_app_signed_up_at) && trim($client->mobile_app_signed_up_at) !== "") {
                                    $mobileAppSignedUpDate = $client->mobile_app_signed_up_at->get()->format("m-d-Y");
                                } else {
                                    $mobileAppSignedUpDate = "";
                                }
                                $id = $client->doc_id;
                                $showClientLink = "show?id=$id";
                                $editClientLink = "edit?id=$id";
                                $deleteClientLink = "delete?id=$id";
                                echo "
                                <tr>
                                    <td class='text-center' style='min-width: 140px; vertical-align: middle'>$realtorName</td>
                                    <td class='text-center' style='min-width: 140px; vertical-align: middle'>$clientName</td>
                                    <td class='text-center' style='max-width: 250px; vertical-align: middle'>$address</td>
                                    <td class='text-center' style='vertical-align: middle'>$city</td>
                                    <td class='text-center' style='vertical-align: middle'>$state</td>
                                    <td class='text-center'>$createdAt</td>
                                    <td class='text-center' style='vertical-align: middle'>$emailInviteSentDate</td>
                                    <td class='text-center' style='vertical-align: middle'>$mobileAppSignedUpDate</td>
                                    <td class='text-center'>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$showClientLink><i data-feather='zoom-in'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark me-2' href=$editClientLink><i data-feather='edit'></i></a>
                                        <a class='btn btn-datatable btn-icon btn-transparent-dark' data-bs-toggle='modal' data-bs-target='#approveUserModal$id'><i data-feather='trash-2'></i></a>                                                                                                                              
                                    </td>
                                </tr>
                                
                                <div class='modal fade' id='approveUserModal$id' tabindex='-1' role='dialog' aria-labelledby='exampleModalCenterTitle' aria-hidden='true'>
                                    <div class='modal-dialog modal-dialog-centered' role='document'>
                                        <div class='modal-content'>
                                            <div class='modal-header d-block'>
                                                <button class='btn-close float-end' type='button' data-bs-dismiss='modal' aria-label='Close'></button>
                                                <h5 class='modal-title text-center' id='exampleModalCenterTitle'>Removal Confirmation</h5>
                                            </div>
                                            <div class='modal-body text-center'>
                                                Do you really want to delete this client ?
                                            </div>
                                            <div class='modal-footer justify-content-center'>
                                                <a class='btn btn-secondary' type='button' data-bs-dismiss='modal'>No</a>
                                                <a class='btn btn-success' type='button' href='$deleteClientLink'>Yes</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                ";
                            };
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';?>
    </div>
</div>
<?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';?>
<script>
    $( document ).ready(function() {
        const datatablesSimple = document.getElementById('datatablesSimple');
        if (datatablesSimple) {
            new simpleDatatables.DataTable(datatablesSimple, {
                /*sortable: false,*/
                columns: [
                    { select: [0,1,3,4,5,6,7], sortable: true },
                    { select: [2,8], sortable: false },
                ]
            });
        }
    });
</script>
</body>
</html>
