<?php
$user = $_SESSION["user"];
$profilePic = isset($user["realtor_photo"]) && trim($user["realtor_photo"]) != '' ? $user["realtor_photo"] : $this->baseUri . '/public/assets/img/illustrations/profiles/profile-4.png';
/*var_dump($profilePic);
die();*/
?>
<nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" style="background-color: #262144!important" id="sidenavAccordion">
    <!-- Sidenav Toggle Button-->
    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle" style="background-color: #00B2A0!important;"><i data-feather="menu"></i></button>
    <!-- Navbar Brand-->
    <!--<a class="navbar-brand pe-3 ps-4 ps-lg-2" href="#">Honeydoo</a>-->
    <img class="navbar-brand pe-3 ps-4 ps-lg-2" src="/../../public/assets/img/HoneyDoo-logo.png">
    <!-- Navbar Items-->
    <ul class="navbar-nav align-items-center ms-auto">
        <!-- User Dropdown-->
        <li class="nav-item dropdown no-caret dropdown-user me-3 me-lg-4">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="img-fluid" src=<?=$profilePic?> /></a>
            <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownUserImage">
                <h6 class="dropdown-header d-flex align-items-center">
                    <img class="dropdown-user-img" src=<?=$profilePic?> />
                    <div class="dropdown-user-details">
                        <div class="dropdown-user-details-name"><?=$user["realtor_title"]?></div>
                        <div class="dropdown-user-details-email"><?=$user["email"]?></div>
                    </div>
                </h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/dashboard/my-profile">
                    <div class="dropdown-item-icon"><i data-feather="user"></i></div>
                    My Profile
                </a>
                <a class="dropdown-item" href="/dashboard/password-verification">
                    <div class="dropdown-item-icon"><i data-feather="lock"></i></div>
                    Change My Password
                </a>
                <a class="dropdown-item" href="/logout">
                    <div class="dropdown-item-icon"><i data-feather="log-out"></i></div>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>