<?php
/* @var $user
 * @var $baseUri
 */
$profPic = isset($user["realtor_photo"]) && trim($user["realtor_photo"]) !== '' ? $user["realtor_photo"] : $this->baseUri . '/public/assets/img/illustrations/profiles/profile-4.png';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    if($_SESSION["user"]["role"] == "ROLE_USER")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';
    } elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';
    }
    ?>
    <title>My Profile</title>
</head>
<body class="nav-fixed">
<?php
if($_SESSION["user"]["role"] == "ROLE_USER")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';
} elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';
}
?>
<div id="layoutSidenav">
    <?php
    if($_SESSION["user"]["role"] == "ROLE_USER")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';
    } elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';
    }
    ?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="user"></i></div>
                                    My Profile
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4 mt-4">
                <div class="row">
                    <div class="col-xl-4">
                        <!-- Profile picture card-->
                        <form action="/dashboard/update-profile-picture?id=<?=$user["realtor_id"]?>" method="post" enctype="multipart/form-data">
                            <div class="card mb-4 mb-xl-0">
                                <div class="card-header text-center">Add/Edit Profile Picture</div>
                                <div class="card-body text-center">
                                    <img class="img-account-profile rounded-circle mb-2" src="<?=$profPic?>" alt="Profile Picture">
                                    <div class="text-center mt-2">
                                        <input class="form-control mb-2" type="file" accept="image/jpeg/png" name="profilePicture">
                                        <button class="btn btn-success" id="uploadPictureButton" type="submit" disabled>Upload picture</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-xl-8">
                        <!-- Account details card-->
                        <div class="card">
                            <div class="card-header text-center">Account Details</div>
                            <div class="card-body">
                                <form action="/dashboard/edit-profile?id=<?=$user["realtor_id"]?>" method="post" class="mt-4">
                                    <div class="row gx-3 mb-3">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputFirstName">Full name</label>
                                            <input class="form-control" id="fullName" name="fullName" placeholder="Enter your full name..." type="text" value="<?= $user["realtor_title"]?>" disabled/>
                                        </div>

                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputEmailAddress">Email address</label>
                                            <input class="form-control" id="emailAddress" name="emailAddress" placeholder="Enter your email address..." type="email" value="<?= $user["email"]?>" disabled/>
                                        </div>
                                    </div>

                                    <div class="row gx-3 mb-3">

                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputLastName">Phone Number</label>
                                            <input class="form-control" id="phoneNumber" name="phoneNumber" placeholder="Enter your phone number..." type="text" value="<?= $user["phone_number"]?>" disabled/>
                                        </div>

                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputOrgName">Company name</label>
                                            <input class="form-control" id="companyName" name="companyName" placeholder="Enter your company name..." type="text" value="<?= $user["realtor_sub_title"]?>" disabled/>
                                        </div>
                                    </div>
                                    <div class="row gx-3 mb-3">
                                        <div class="col">
                                            <label class="small mb-1" for="notes">About me</label>
                                            <textarea class="lh-base form-control" id="aboutMe" name="aboutMe" placeholder="Add a short description for your clients to read..." type="text" rows="2" style="resize: none" disabled><?= $user["about_me"] ?? "" ?></textarea>
                                        </div>
                                    </div>
                                    <!-- Save changes button-->
                                    <div class="text-center mb-1">
                                        <button class="btn btn-primary" id="editButton" type="button">Edit</button>
                                        <button class="btn btn-success" id="saveButton" type="submit" style="display: none">Save Changes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <?php
        if($_SESSION["user"]["role"] == "ROLE_USER")
        {
            include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';
        } elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
        {
            include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';
        }
        ?>
    </div>
</div>
<?php
if($_SESSION["user"]["role"] == "ROLE_USER")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';
} elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';
}
?>
<script>
    $( document ).ready(function() {
        $("#editButton").click(function () {
            $(this).hide();
            $("#saveButton").show();
            $("input").prop('disabled', false);
            $("#aboutMe").prop('disabled', false);
        })
        $("input:file").change(function (){
            if($(this).val())
            {
                $("#uploadPictureButton").prop('disabled', false);
            } else {
                $("#uploadPictureButton").prop('disabled', true);
            }
        });
    });
</script>
</body>
</html>
