<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/security/header.phtml';?>
    <title>Password Reset Successful - HoneyDoo Realtor Portal</title>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="text-center">
                <img src="https://realtors.honeydoo.io/app/Ressources/assets/img/HoneyDoo-logo.png" width="400" style="margin: 50px 0 25px;">
            </div>
            <div class="container-xl px-4">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header justify-content-center"><h3 class="fw-light my-4 text-center">Your password has been changed.</h3></div>
                            <div class="card-body">
                                <div class="small mb-3 text-center">
                                    Congratulations! Your password has been changed successfully.
                                </div>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="/login">Return to login</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/security/footer.phtml';?>
    </div>
</div>
</body>
</html>
