<?php
/* @var $errorMessage */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/security/header.phtml';?>
    <title>Change Password Form - HoneyDoo Realtor Portal</title>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="text-center">
                <img src="https://realtors.honeydoo.io/app/Ressources/assets/img/HoneyDoo-logo.png" width="400" style="margin: 50px 0 25px;">
            </div>
            <div class="container-xl px-4">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <!-- Change password form-->
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header justify-content-center"><h3 class="fw-light my-4 text-center">Enter your new password</h3></div>
                            <div class="card-body">
                                <!-- Forgot password form-->
                                <form action="/reset-password/reset" method="post">
                                    <?php
                                    if(isset($errorMessage))
                                    {
                                        echo "<div class='alert alert-danger'>$errorMessage</div>";
                                    }
                                    ?>
                                <!-- Form Group (password)-->
                                    <div class="mb-3">
                                        <label class="small mb-1" for="password">Password</label>
                                        <input class="form-control" name="password" type="password" placeholder="Enter your new password" required/>
                                        <div style="color: grey; font-size: small">
                                            <small>Your password must be at least 8 characters long and contains a special character, e.g. !#$@.,:;</small>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <label class="small mb-1" for="confirmPassword">Confirm Password</label>
                                        <input class="form-control" name="confirmPassword" type="password" placeholder="Confirm your password" required/>
                                    </div>
                                    <!-- Form Group (submit options)-->
                                    <div class="text-center">
                                        <button class="btn btn-success text-center" type="submit">Reset Password</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        <?php include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/security/footer.phtml';?>
    </div>
</div>
</body>
</html>
