<?php
/* @var $errorMessage */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    if($_SESSION["user"]["role"] == "ROLE_USER")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/header.phtml';
    } elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/header.phtml';
    }
    ?>
    <title>Change Password</title>
</head>
<body class="nav-fixed">
<?php
if($_SESSION["user"]["role"] == "ROLE_USER")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/navbar.phtml';
} elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/navbar.phtml';
}
?>
<div id="layoutSidenav">
    <?php
    if($_SESSION["user"]["role"] == "ROLE_USER")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/sidebar.phtml';
    } elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
    {
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/sidebar.phtml';
    }
    ?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="lock"></i></div>
                                    Change Password
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-4">
                <div class="row">
                    <div class="col-xl-4">
                    </div>
                    <div class="col-xl-4">
                        <div class="card mb-4">
                            <div class="card-header text-center">New Password</div>
                            <div class="card-body">
                                <form action="/dashboard/change-password" method="post">
                                    <?php
                                    if(isset($errorMessage))
                                    {
                                        echo "<div class='alert alert-danger'>$errorMessage</div>";
                                    }
                                    ?>
                                    <div class="row gx-3 mb-1">
                                        <div class="mb-2">
                                            <label class="small mb-1" for="password">New Password</label>
                                            <input class="form-control" type="password" name="newPassword" placeholder="Enter your new password..." required/>
                                        </div>
                                    </div>
                                    <div class="row gx-3 mb-1">
                                        <div class="mb-2">
                                            <label class="small mb-1" for="password">Confirm Password</label>
                                            <input class="form-control" type="password" name="confirmPassword" placeholder="Confirm your new password..." required/>
                                        </div>
                                    </div>
                                    <div class="align-items-center justify-content-between mt-1 text-center">
                                        <input class="btn btn-success" type="submit" value="Save Changes">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4">
                    </div>
                </div>
            </div>
        </main>
        <?php
        if($_SESSION["user"]["role"] == "ROLE_USER")
        {
            include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/footer.phtml';
        } elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
        {
            include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/footer.phtml';
        }
        ?>
    </div>
</div>
<?php
if($_SESSION["user"]["role"] == "ROLE_USER")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/realtor/scripts.phtml';
} elseif ($_SESSION["user"]["role"] == "ROLE_ADMIN")
{
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/admin/scripts.phtml';
}
?>
</body>
</html>
